# Generated by Django 3.2.7 on 2021-09-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('screen', models.FloatField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=10, null=True)),
                ('OS', models.CharField(blank=True, max_length=10, null=True)),
                ('graphics', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(max_length=10)),
                ('frontcamera', models.CharField(blank=True, max_length=10, null=True)),
                ('backcamera', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('screen', models.FloatField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=10, null=True)),
                ('OS', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(max_length=10)),
                ('frontcamera', models.CharField(blank=True, max_length=10, null=True)),
                ('backcamera', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='OS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='backcamera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frontcamera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='graphics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AlterField(
            model_name='product',
            name='serialNo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
